# Generated by Django 6.0.1 on 2026-01-19 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('role', models.CharField(choices=[('Worker', 'Worker'), ('Employer', 'Employer')], max_length=10)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('pay', models.IntegerField()),
                ('pay_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Hourly', 'Hourly')], max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('required_workers', models.IntegerField(default=1)),
                ('applicants', models.ManyToManyField(blank=True, related_name='applied_jobs', to='app.userprofile')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to='app.userprofile')),
            ],
        ),
    ]
